services:
  postgres_dev:
    image: postgres:17
    container_name: postgres_dev
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apollo_job_board_api
    depends_on:
      - postgres_dev
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  postgres_data: