
services:
  postgres_dev:
    image: postgres:17
    container_name: postgres_dev
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apollo_job_board_migrate
    depends_on:
      postgres_dev:
        condition: service_healthy
    env_file:
      - ./.env
    command: ["sh", "-c", "wait-on tcp:$POSTGRES_HOST:$POSTGRES_PORT && npx prisma db push"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apollo_job_board_api
    depends_on:
      - postgres_dev
      - migrate
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma:/app/prisma

volumes:
  postgres_data: